# Generated by Django 5.1.3 on 2024-11-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_rooms_size"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rooms",
            constraint=models.UniqueConstraint(
                fields=("hotel", "roomnumber"), name="unique_room_per_hotel"
            ),
        ),
    ]
