# Generated by Django 5.1.3 on 2024-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rooms_unique_room_per_hotel"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rooms",
            name="unique_room_per_hotel",
        ),
        migrations.RenameField(
            model_name="rooms",
            old_name="roomnumber",
            new_name="room_number",
        ),
        migrations.AddConstraint(
            model_name="rooms",
            constraint=models.UniqueConstraint(
                fields=("hotel", "room_number"), name="unique_room_per_hotel"
            ),
        ),
    ]
