# Generated by Django 5.1.3 on 2024-11-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_rooms_unique_room_per_hotel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="booking_id",
        ),
    ]
